# Make file for KRR IREC Paylaod
#
all:
	gcc ~/C_Files/KRR/IREC_2020_Payload/SensorTests/src/MPU6050Test.c ~/C_Files/KRR/IREC_2020_Payload/SensorTests/src/main.c ~/C_Files/KRR/IREC_2020_Payload/SensorTests/src/drivers/GPSV2.c -pedantic -Wall -Wextra -lwiringPi -o Payload
